const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'Computer',
    price: 3799.99,
    img: './images/komp1.webp',
    desc: ` Noutbuk Lenovo Legion 5 15ACH6H (82JU00BLRK) `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'Phones',
    price: 799.99,
    img: './images/phone1.webp',
    desc: `HUAWEI Nova 9 SE 8GB / 128GB Starry Blue `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'Watches',
    price: 599.99,
    img: './images/watch1.webp',
    desc: `HUAWEI Watch GT 3 Active Black 42mm`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'Computer',
    price: 1999.80,
    img: './images/komp2.webp',
    desc: `Noutbuk MSI GF63 Thin 10SCXR-222US (9S7-16R512-630)`,
  },
  {
    id: 5,
    title: 'Laptops',
    category: 'Phones',
    price: 899.99,
    img: './images/phone2.webp',
    desc: `Xiaomi Poco Pro X4 6/128GB Yellow`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'Watches',
    price: 150.99,
    img: './images/watch2.webp',
    desc: `Xiaomi Redmi watch 2 lite/BHR5436GL`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'Computer',
    price: 4599.99,
    img: './images/komp3.webp',
    desc: `Noutbuk Asus ROG Zephyrus M16 GU603HR-K8040 (90NR04R1-M02330) `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'Phones',
    price: 1599.99,
    img: './images/phone3.webp',
    desc: `Xiaomi 12X 8GB/128GB Purple `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'Watches',
    price: 579.99,
    img: './images/watch3.webp',
    desc: `HUAWEI Watch GT 3 Active Black 46 mm`,
  },
  {
    id: 10,
    title: 'quarantine buddy',
    category: 'Computer',
    price: 1679.99,
    img: './images/komp5.webp',
    desc: `Noutbuk Asus VivoBook X513EA-BQ1916 (90NB0SG4-M29260)`,
  },
  {
    id: 11,
    title: 'quarantine buddy',
    category: 'Phones',
    price: 879.99,
    img: './images/phone4.webp',
    desc: `Xiaomi Redmi Note 11 Pro 8GB/128GB Atlantic Blue.`,
  },
  {
    id: 12,
    title: 'quarantine buddy',
    category: 'Watches',
    price: 1099.99,
    img: './images/watch4.webp',
    desc: `Apple Watch 7 41 mm Green MKN03`,
  },
  {
    id: 13,
    title: 'quarantine buddy',
    category: 'Computer',
    price: 6119.99,
    img: './images/komp4.webp',
    desc: `Noutbuk HP Omen 15-DH1037UR (363Z9EA)`,
  },
  {
    id: 14,
    title: 'quarantine buddy',
    category: 'Phones',
    price: 1699.99,
    img: './images/phone5.webp',
    desc: `iPhone SE GEN.3 256GB-Red`,
  },
  {
    id: 15,
    title: 'quarantine buddy',
    category: 'Watches',
    price: 567.99,
    img: './images/watch5.webp',
    desc: `HUAWEI Watch GT 3 Elegant White 42mm`,
  },
  {
    id: 16,
    title: 'quarantine buddy',
    category: 'Watches',
    price: 1290.99,
    img: './images/watch6.webp',
    desc: `Apple Watch 7 41 mm Red MKN23`,
  },
  
];
export default menu;
